max_u32: &max_u32 4294967295

comment_prefix: '//'
root_kind: root
root_expected_first_tokens:
  - '`buf`'
  - '`fn`'
  - '`import`'
  - '`init`'
  - '`run`'
import_index_key: '@import'
type_transpilation:
  bool: u32

kinds: { } # defined in other config files
