max_u32: &max_u32 4294967295

kinds:
  ident:
    pattern_parts:
      - char_ranges:
          - { start: 'a', end: 'z' }
          - { start: 'A', end: 'Z' }
          - { start: '_', end: '_' }
        min_length: 1
        max_length: 1
      - char_ranges:
          - { start: 'a', end: 'z' }
          - { start: 'A', end: 'Z' }
          - { start: '0', end: '9' }
          - { start: '_', end: '_' }
        min_length: 0
        max_length: *max_u32
    display_name: identifier

  string:
    pattern_parts:
      - char_ranges:
          - { start: '"', end: '"' }
        min_length: 1
        max_length: 1
      - exception_char_ranges:
          - { start: '"', end: '"' }
        min_length: 0
        max_length: *max_u32
      - char_ranges:
          - { start: '"', end: '"' }
        min_length: 1
        max_length: 1
    display_name: string literal

  tilde: { string: '~' }
  dot: { string: '.' }
  comma: { string: ',' }
  eq: { string: '=' }
  plus: { string: '+' }
  hyphen: { string: '-' }
  star: { string: '*' }
  slash: { string: '/' }
  percent: { string: '%' }
  excl_mark: { string: '!' }
  colon: { string: ':' }
  semicolon: { string: ';' }
  open_parenthesis: { string: '(' }
  close_parenthesis: { string: ')' }
  open_bracket: { string: '{' }
  close_bracket: { string: '}' }
  open_angle_bracket: { string: '<' }
  close_angle_bracket: { string: '>' }
  compare_le: { string: '<=' }
  compare_ge: { string: '>=' }
  compare_eq: { string: '==' }
  compare_ne: { string: '!=' }
  and: { string: '&&' }
  or: { string: '||' }
  arrow: { string: '->' }
  import_kw: { string: 'import' }
  buf_kw: { string: 'buf' }
  init_kw: { string: 'init' }
  run_kw: { string: 'run' }
  var_kw: { string: 'var' }
  fn_kw: { string: 'fn' }
  native_kw: { string: 'native' }
  return_kw: { string: 'return' }
