max_u32: &max_u32 4294967295

comment_prefix: '//'
root_kind: root
root_expected_first_tokens:
  - '`buf`'
  - '`fn`'
  - '`import`'
  - '`init`'
  - '`run`'
import_index_key: '@import'
type_transpilation:
  bool: u32

kinds:
  root:
    min_repeat: 0
    max_repeat: *max_u32
    choice:
      - buffer_item
      - fn_item
      - import_item
      - init_item
      - run_item
